//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModelContext : DbContext
    {
        public DbModelContext()
            : base("name=DbModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EvolutiaPretului> EvolutiaPretului { get; set; }
        public virtual DbSet<IstoricCautari> IstoricCautari { get; set; }
        public virtual DbSet<Produs> Produs { get; set; }
        public virtual DbSet<UrmarireProdus> UrmarireProdus { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
        public virtual DbSet<Vanzator> Vanzator { get; set; }
    }
}
