//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceEvolution
    {
        public System.Guid Id { get; set; }
        public string Price { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
