//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs()
        {
            this.EvolutiaPretului = new HashSet<EvolutiaPretului>();
            this.UrmarireProdus = new HashSet<UrmarireProdus>();
        }
    
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string Denumire { get; set; }
        public string Pret { get; set; }
        public string Stock { get; set; }
        public string Url_Imagine { get; set; }
        public Nullable<System.Guid> Id_Vanzator { get; set; }
        public string SKU { get; set; }
        public string EAN { get; set; }
        public Nullable<System.DateTime> Data_Creat { get; set; }
        public string Cod_Denumire_Produs { get; set; }
        public Nullable<bool> Sters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolutiaPretului> EvolutiaPretului { get; set; }
        public virtual Vanzator Vanzator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrmarireProdus> UrmarireProdus { get; set; }
    }
}
