//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PriceEvolutions = new HashSet<PriceEvolution>();
            this.ProductFollows = new HashSet<ProductFollow>();
        }
    
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string Stock { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> RetailerID { get; set; }
        public string SKU { get; set; }
        public string EAN { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ProductDescriptionCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceEvolution> PriceEvolutions { get; set; }
        public virtual Retailer Retailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFollow> ProductFollows { get; set; }
    }
}
