//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrmarireProdus
    {
        public System.Guid Id { get; set; }
        public System.Guid Id_Produs { get; set; }
        public System.Guid Id_Utilizator { get; set; }
        public decimal Limita_pret { get; set; }
        public bool UtilizatorNotificat { get; set; }
        public Nullable<System.DateTime> DataNotificarii { get; set; }
        public bool Invalid { get; set; }
    
        public virtual Produs Produs { get; set; }
        public virtual Utilizator Utilizator { get; set; }
    }
}
