//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizator()
        {
            this.UrmarireProdus = new HashSet<UrmarireProdus>();
        }
    
        public System.Guid Id { get; set; }
        public string Nume_Utilizator { get; set; }
        public string Parola { get; set; }
        public string Email { get; set; }
        public string Numar_Telefon { get; set; }
        public string Porecla { get; set; }
        public string Rol { get; set; }
        public string CheieParola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrmarireProdus> UrmarireProdus { get; set; }
    }
}
