//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Utilities.DatabaseUtilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vanzator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vanzator()
        {
            this.Produs = new HashSet<Produs>();
        }
    
        public System.Guid Id { get; set; }
        public string Nume { get; set; }
        public string Site { get; set; }
        public string Cod_Tara { get; set; }
        public string Delimitator_Zecimala { get; set; }
        public Nullable<bool> Sters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produs> Produs { get; set; }
    }
}
