// <auto-generated />
namespace DatabaseModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedadminseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedadminseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201901071322341_added-admin-seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
