// <auto-generated />
namespace DatabaseModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedpasswords_saltcheie_parolatoutilizator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpasswords_saltcheie_parolatoutilizator));
        
        string IMigrationMetadata.Id
        {
            get { return "201901131505236_added-passwords_salt-cheie_parola-to-utilizator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
